config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  # CREATE
  get "pets/new", to: "pets#new"
  post "pets", to: "pets#create"

  # READ
  root "pets#index"
  get "pets/:id", to: "pets#show", as: :pet


  # UPDATE
  get "pets/:id/edit", to: "pets#edit", as: :edit_pet
  patch "pets/:id/", to: "pets#update"

  # DELETE

  delete "pets/:id", to: "pets#destroy"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/pet.rb
class Pet < ApplicationRecord
  SPECIES = ["dog", "cat", "bird"]

  validates :name, presence: true
  validates :species, inclusion: SPECIES
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController

  def index
    @pets = Pet.all
  end

  def show
    @pet = Pet.find(params[:id])
  end

  def new
    @pet = Pet.new
  end

  def create
    @pet = Pet.new(pet_params)
    if @pet.save
      redirect_to pet_path(@pet)
    else
      render :new
    end
  end

  def edit
    @pet = Pet.find(params[:id])
  end

  def update
    @pet = Pet.find(params[:id])
    @pet.update(pet_params)
    redirect_to pet_path(@pet)
  end

  def destroy
    @pet = Pet.find(params[:id])
    @pet.destroy
    redirect_to root_path, status: :see_other
  end

  private

  def pet_params
    params.require(:pet).permit(:name, :address, :species, :date)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LostPets</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pets/_form.html.erb
<%= form_with model: pet do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :address %>
  <%= f.text_field :address %>
  <%= f.label :species %>
  <%= f.select :species, Pet::SPECIES %>
  <%= f.label :date %>
  <%= f.date_field :date %>
  <%= f.submit %>
<% end %>

app/views/pets/edit.html.erb
<%= render "form", pet: @pet %>

app/views/pets/index.html.erb
<h1>all pets</h1>

<ul>
  <% @pets.each do |pet| %>
    <li>
      <%= link_to pet.name, pet_path(pet) %>
    </li>
  <% end %>
</ul>


<%= link_to "add a pet", pets_new_path %>

app/views/pets/new.html.erb
<%= form_with model: @pet do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :address %>
  <%= f.text_field :address %>
  <%= f.label :species %>
  <%= f.select :species, Pet::SPECIES %>
  <%= f.label :date %>
  <%= f.date_field :date %>
  <%= f.submit %>

<% end %>

app/views/pets/show.html.erb
<h1><%= @pet.name %></h1>

<p><%= @pet.species %></p>
<p><%= @pet.date %></p>
<p><%= @pet.address %></p>


<%= link_to "back to list", root_path %>

<%= link_to "Kill this pet", pet_path(@pet),
 data: {turbo_method: :delete, turbo_confirm: "NOOOOOOOOO"}%>